# Generated by Django 5.2.17 on 2026-09-28 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                ("national_id", models.CharField(max_length=24, verbose_name="Cédula")),
                ("job_title", models.CharField(max_length=120, verbose_name="Cargo")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("administrative", "Administrativo"),
                            ("worker", "Obrero"),
                            ("hourly_teacher", "Profesor por horas / cátedra"),
                            ("full_time_teacher", "Profesor tiempo completo"),
                        ],
                        max_length=24,
                        verbose_name="Tipo de contrato",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Fecha de ingreso")),
                (
                    "monthly_salary_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Sueldo mensual (USD)",
                    ),
                ),
                (
                    "hours_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Horas dictadas al mes",
                    ),
                ),
                (
                    "hourly_rate_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor hora (USD)",
                    ),
                ),
                (
                    "regular_bonus_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Bonos regulares salariales (USD)",
                    ),
                ),
                (
                    "transport_bonus_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Bono de transporte (USD)",
                    ),
                ),
                (
                    "scale_bonus_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Bono de escalafón (USD)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="institutions.institution",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "empleado",
                "verbose_name_plural": "empleados",
                "ordering": ["last_name", "first_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution", "national_id"),
                        name="unique_employee_id_per_institution",
                    )
                ],
            },
        ),
    ]
