# Generated by Django 5.2.17 on 2026-09-28 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalRuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, verbose_name="Nombre de la versión legal"
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="Vigente desde")),
                (
                    "minimum_monthly_salary_bs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=16,
                        verbose_name="Salario mínimo mensual de referencia (Bs)",
                    ),
                ),
                (
                    "ivss_employee_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=7,
                        verbose_name="Tasa IVSS trabajador",
                    ),
                ),
                (
                    "ivss_cap_minimum_wages",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Tope IVSS (salarios mínimos)",
                    ),
                ),
                (
                    "faov_employee_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=7,
                        verbose_name="Tasa FAOV trabajador",
                    ),
                ),
                (
                    "unemployment_employee_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=7,
                        verbose_name="Tasa paro forzoso trabajador",
                    ),
                ),
                (
                    "unemployment_cap_minimum_wages",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="Tope paro forzoso (salarios mínimos)",
                    ),
                ),
                (
                    "additional_benefit_days_per_year",
                    models.PositiveSmallIntegerField(
                        default=2,
                        verbose_name="Días adicionales de prestaciones por año",
                    ),
                ),
                (
                    "additional_benefit_days_cap",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Tope acumulado de días adicionales"
                    ),
                ),
            ],
            options={
                "verbose_name": "parámetro legal global",
                "verbose_name_plural": "parámetros legales globales",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Inicio del período")),
                ("period_end", models.DateField(verbose_name="Fin del período")),
                (
                    "exchange_rate_snapshot",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Tasa BCV aplicada (Bs/USD)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_runs",
                        to="institutions.institution",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "legal_rules",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.legalruleset",
                        verbose_name="Reglas legales aplicadas",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institutions.institutionpolicy",
                        verbose_name="Política aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "corrida de nómina",
                "verbose_name_plural": "corridas de nómina",
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayrollResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salary_base_monthly_bs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Salario base mensual (Bs)",
                    ),
                ),
                (
                    "normal_monthly_bs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Salario normal mensual (Bs)",
                    ),
                ),
                (
                    "normal_daily_bs",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Salario normal diario (Bs)",
                    ),
                ),
                (
                    "utility_allowance_daily_bs",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Alícuota utilidades diaria (Bs)",
                    ),
                ),
                (
                    "vacation_allowance_daily_bs",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Alícuota vacacional diaria (Bs)",
                    ),
                ),
                (
                    "integral_daily_bs",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Salario integral diario (Bs)",
                    ),
                ),
                (
                    "cestaticket_bs",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Cestaticket (Bs)"
                    ),
                ),
                (
                    "ivss_bs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="Retención IVSS (Bs)",
                    ),
                ),
                (
                    "faov_bs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="Retención FAOV (Bs)",
                    ),
                ),
                (
                    "unemployment_bs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="Retención paro forzoso (Bs)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employees.employee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="payroll.payrollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado de nómina",
                "verbose_name_plural": "resultados de nómina",
                "ordering": ["employee__last_name", "employee__first_name"],
            },
        ),
        migrations.CreateModel(
            name="QuarterlyAccrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quarter_end", models.DateField(verbose_name="Cierre del trimestre")),
                (
                    "integral_daily_bs",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Salario integral diario (Bs)",
                    ),
                ),
                (
                    "credited_days",
                    models.PositiveSmallIntegerField(verbose_name="Días acreditados"),
                ),
                (
                    "amount_bs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Monto acreditado (Bs)",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefit_accruals",
                        to="employees.employee",
                    ),
                ),
                (
                    "payroll_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quarterly_accrual",
                        to="payroll.payrollresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "acumulación trimestral de prestaciones",
                "verbose_name_plural": "acumulaciones trimestrales de prestaciones",
                "ordering": ["quarter_end"],
            },
        ),
        migrations.AddConstraint(
            model_name="payrollresult",
            constraint=models.UniqueConstraint(
                fields=("run", "employee"), name="unique_employee_per_payroll_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="quarterlyaccrual",
            constraint=models.UniqueConstraint(
                fields=("employee", "quarter_end"),
                name="unique_employee_quarter_accrual",
            ),
        ),
    ]
