# Generated by Django 5.2.17 on 2026-09-28 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_institutionmembership"),
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="legalruleset",
            constraint=models.UniqueConstraint(
                fields=("effective_from",), name="unique_global_rules_effective_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("institution", "period_start", "period_end"),
                name="unique_payroll_period_per_institution",
            ),
        ),
    ]
