# Generated by Django 5.2.17 on 2026-09-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_legalruleset_unique_global_rules_effective_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollresult",
            name="calculation_snapshot",
            field=models.JSONField(
                default=dict, verbose_name="Datos de cálculo congelados"
            ),
        ),
        migrations.AddField(
            model_name="payrollresult",
            name="contract_type_snapshot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("administrative", "Administrativo"),
                    ("worker", "Obrero"),
                    ("hourly_teacher", "Profesor por horas / cátedra"),
                    ("full_time_teacher", "Profesor tiempo completo"),
                ],
                max_length=24,
                verbose_name="Contrato al procesar",
            ),
        ),
        migrations.AddField(
            model_name="payrollresult",
            name="employee_id_snapshot",
            field=models.CharField(
                blank=True, max_length=24, verbose_name="Cédula al procesar"
            ),
        ),
        migrations.AddField(
            model_name="payrollresult",
            name="employee_name_snapshot",
            field=models.CharField(
                blank=True, max_length=220, verbose_name="Nombre al procesar"
            ),
        ),
        migrations.AddField(
            model_name="payrollresult",
            name="salary_base_daily_bs",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=18,
                verbose_name="Salario base diario (Bs)",
            ),
            preserve_default=False,
        ),
    ]
