# Generated by Django 5.2.17 on 2026-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_payrollresult_calculation_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollrun",
            name="institution_name_snapshot",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Institución al procesar"
            ),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="institution_tax_id_snapshot",
            field=models.CharField(
                blank=True, max_length=24, verbose_name="RIF al procesar"
            ),
        ),
        migrations.AlterField(
            model_name="legalruleset",
            name="faov_employee_rate",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Proporción decimal; por ejemplo, 0.01 equivale a 1 %.",
                max_digits=7,
                verbose_name="Tasa FAOV trabajador",
            ),
        ),
        migrations.AlterField(
            model_name="legalruleset",
            name="ivss_employee_rate",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Proporción decimal; por ejemplo, 0.04 equivale a 4 %.",
                max_digits=7,
                verbose_name="Tasa IVSS trabajador",
            ),
        ),
        migrations.AlterField(
            model_name="legalruleset",
            name="unemployment_employee_rate",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Proporción decimal; por ejemplo, 0.005 equivale a 0,5 %.",
                max_digits=7,
                verbose_name="Tasa paro forzoso trabajador",
            ),
        ),
    ]
