# Generated by Django 5.2.17 on 2026-09-28 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=160, verbose_name="Nombre del liceo"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razón social"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=24, verbose_name="RIF"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "institución",
                "verbose_name_plural": "instituciones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Versión")),
                ("effective_from", models.DateField(verbose_name="Vigente desde")),
                (
                    "bcv_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        verbose_name="Tasa BCV (Bs/USD)",
                    ),
                ),
                (
                    "utility_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Días de utilidades"
                    ),
                ),
                (
                    "vacation_days",
                    models.PositiveSmallIntegerField(
                        default=15, verbose_name="Días de bono vacacional"
                    ),
                ),
                (
                    "vacation_days_per_year",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Días adicionales por año de servicio"
                    ),
                ),
                (
                    "cestaticket_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        max_digits=12,
                        verbose_name="Cestaticket (USD)",
                    ),
                ),
                (
                    "docente_scale_active",
                    models.BooleanField(
                        default=False, verbose_name="Escalafón docente activo"
                    ),
                ),
                (
                    "transport_is_salary",
                    models.BooleanField(
                        default=False, verbose_name="Transporte salarial"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="institutions.institution",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración del liceo",
                "verbose_name_plural": "configuraciones del liceo",
                "ordering": ["-effective_from", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution", "version"),
                        name="unique_institution_policy_version",
                    ),
                    models.UniqueConstraint(
                        fields=("institution", "effective_from"),
                        name="unique_institution_policy_date",
                    ),
                ],
            },
        ),
    ]
