# Generated by Django 5.2.17 on 2026-09-28 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador del liceo"),
                            ("operator", "Operador de nómina"),
                            ("viewer", "Solo lectura"),
                        ],
                        default="operator",
                        max_length=16,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="institutions.institution",
                        verbose_name="Institución",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "membresía de institución",
                "verbose_name_plural": "membresías de instituciones",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institution", "user"),
                        name="unique_user_membership_per_institution",
                    )
                ],
            },
        ),
    ]
